### ISSUE TITLE
Serve karma board over HTTPS

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/heyburrito#6]
HTTPS is the new normal on the web, so we should move our server over.

It looks like if we setup our domain with Digital Ocean, then we can configure their load balancer to create and manage a cert with Let's Encrypt for us automatically:

https://www.digitalocean.com/docs/networking/load-balancers/how-to/ssl-termination/

# TODO
* [ ] change devedmonton.com to use Digital Ocean DNS name servers (@MarkBennett)
* [ ] change load balancer forwarding rules to use Let's Encrypt certificates with the `devedmonton.com` domain

**Comment by MarkBennett** [comment]
@j-rewerts heads up. I'll take care of changing the name servers. This is a good way to share them anyway.

**Comment by j-rewerts** [comment]
One more todo:

- [ ] Add support for websocket HTTPS upgrade

I think that one is the real blocking issue.

**Comment by MarkBennett** [comment]
Just a heads up that I was able to get a site running using Rio (https://rio.io) to serve a dockerized app on top of DO Kubernetes and deploying using GitHub Actions. It was pretty fast to setup and get running so we might want to try something like this for Hey Burrito?

This is the site:

https://alphabeta-staging.burmis.ca/

The repo is private but I can pull out the bits that are important and put them up in a Gist.
